In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import qr

# Задание 8. QR-алгоритм. Решение полной проблемы собственных значений

In [2]:
m = 5

Симметричная матрица m на m

In [3]:
A = np.random.uniform(-100, 100, (m, m))
A = A * A.T

In [4]:
B = A

In [5]:
S = np.eye(m, m)

QR-алгоритм

In [16]:
for k in range(1000):
    Q, R = qr(B)
    B = R @ Q
    S = S @ Q

Собственные числа, найденные QR-алгоритмом

In [17]:
np.round(np.diag(B), 4)

array([ 18395.2794, -12441.2025,  11555.3942,   1023.9407,   -636.1318])

Собственные числа, найденные numpy

In [18]:
np.round(np.linalg.eigvals(A), 4)

array([-12441.2025,  18395.2794,  11555.3942,   -636.1318,   1023.9407])

Собственные векторы, найденные numpy

In [24]:
np.round(np.linalg.eig(A)[1], 4)

array([[-0.4853, -0.4988, -0.3338, -0.5526, -0.3144],
       [-0.4616,  0.3581,  0.3222, -0.4502,  0.5935],
       [ 0.2618,  0.6407, -0.0324, -0.4852, -0.5334],
       [-0.6048,  0.4529, -0.4299,  0.4697, -0.154 ],
       [ 0.3421,  0.0859, -0.7739, -0.1896,  0.4906]])

Собственные векторы, найденные QR-алгоритмом

In [28]:
np.round(S, 4)

array([[ 0.4988,  0.4853, -0.3338, -0.3144,  0.5526],
       [-0.3581,  0.4616,  0.3222,  0.5935,  0.4502],
       [-0.6407, -0.2618, -0.0324, -0.5334,  0.4852],
       [-0.4529,  0.6048, -0.4299, -0.154 , -0.4697],
       [-0.0859, -0.3421, -0.7739,  0.4906,  0.1896]])

Равенство Av = λv выполняется (для собственных векторов, найденные QR-алгоритмом)

In [29]:
for i in range(m):
    print(np.round(A @ S.T[i] - np.diag(B)[i] * S.T[i], 4))

[ 0. -0. -0. -0. -0.]
[-0. -0.  0. -0.  0.]
[ 0.  0. -0.  0.  0.]
[-0.  0.  0.  0.  0.]
[ 0. -0. -0.  0. -0.]
